docker-build:
    image: docker:latest
    stage: build
    services:
        - docker:dind
    script:
        - docker info
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker build -t $CI_REGISTRY/albina-euregio/albina-docker .
        - docker push $CI_REGISTRY/albina-euregio/albina-docker
